import { guardedFetch } from "./fetcher";
import type { RobotsGate } from "./robots";
import type { Confidence, ProbeResult, TechCategory, TechMatch } from "@/lib/types";

interface HintRule {
  name: string;
  category: TechCategory;
  /**
   * Every pattern must match. Multi-pattern rules exist because single generic
   * directory names (/components/, /modules/, /checkouts/) appear in plenty of
   * robots.txt files that have nothing to do with the platform that popularised
   * them; requiring the co-occurring set is what makes them evidence.
   */
  patterns: RegExp[];
  label: string;
  confidence: Confidence;
}

interface PathProbe {
  path: string;
  name: string;
  category: TechCategory;
  /** Statuses that suggest the resource actually exists. */
  accept: number[];
  /** Body pattern that upgrades the match from "path exists" to "confirmed". */
  confirm: RegExp;
}

const ROBOTS_HINTS: HintRule[] = [
  { name: "WordPress", category: "CMS", patterns: [/disallow:\s*\/wp-(admin|includes)/i], label: "robots.txt disallows /wp-admin/", confidence: "high" },
  { name: "WordPress", category: "CMS", patterns: [/wp-sitemap\.xml/i], label: "robots.txt points at wp-sitemap.xml", confidence: "high" },
  { name: "Shopify", category: "Ecommerce", patterns: [/disallow:\s*\/a\/downloads\//i], label: "robots.txt disallows /a/downloads/ (Shopify default)", confidence: "high" },
  // /checkouts/ alone is ordinary ecommerce; the stock Shopify trio is not.
  { name: "Shopify", category: "Ecommerce", patterns: [/disallow:\s*\/checkouts?\//i, /disallow:\s*\/cart/i, /disallow:\s*\/orders/i], label: "robots.txt matches the stock Shopify disallow set", confidence: "medium" },
  { name: "Joomla", category: "CMS", patterns: [/disallow:\s*\/administrator\//i], label: "robots.txt disallows /administrator/", confidence: "high" },
  // Requires three stock Joomla directories together: any one of them alone is
  // a generic name that appears in unrelated robots.txt files.
  { name: "Joomla", category: "CMS", patterns: [/disallow:\s*\/components\//i, /disallow:\s*\/modules\//i, /disallow:\s*\/(plugins|libraries|installation)\//i], label: "robots.txt disallows the stock Joomla directory set", confidence: "medium" },
  { name: "Drupal", category: "CMS", patterns: [/disallow:\s*\/core\//i], label: "robots.txt disallows /core/ (Drupal 8+)", confidence: "high" },
  { name: "Drupal", category: "CMS", patterns: [/disallow:\s*\/user\/(login|register)/i, /disallow:\s*\/(node|admin)\//i], label: "robots.txt disallows /user/login and /node/", confidence: "medium" },
  { name: "Ghost", category: "CMS", patterns: [/disallow:\s*\/ghost\//i], label: "robots.txt disallows /ghost/", confidence: "high" },
  { name: "Wix", category: "Site Builder", patterns: [/noflashhtml|disallow:\s*\/_api\//i], label: "robots.txt contains Wix-specific rules", confidence: "high" },
  { name: "Squarespace", category: "Site Builder", patterns: [/squarespace/i], label: "robots.txt names Squarespace", confidence: "high" },
  { name: "Squarespace", category: "Site Builder", patterns: [/disallow:\s*\/config\b/i, /disallow:\s*\/api\//i], label: "robots.txt matches the Squarespace default set", confidence: "medium" },
  { name: "Magento", category: "Ecommerce", patterns: [/disallow:\s*\/(checkout\/cart|customer\/account)\//i], label: "robots.txt disallows Magento cart paths", confidence: "medium" },
];

const SITEMAP_HINTS: HintRule[] = [
  { name: "WordPress", category: "CMS", patterns: [/wp-sitemap|\/wp-content\//i], label: "sitemap references WordPress core paths", confidence: "high" },
  { name: "WordPress", category: "CMS", patterns: [/main-sitemap\.xsl|yoast/i], label: "sitemap generated by Yoast SEO (WordPress)", confidence: "high" },
  { name: "WordPress", category: "CMS", patterns: [/(post|page|category)-sitemap\.xml/i], label: "sitemap index uses WordPress naming", confidence: "medium" },
  { name: "Shopify", category: "Ecommerce", patterns: [/sitemap_products_\d+\.xml|sitemap_collections_\d+\.xml/i], label: "sitemap index uses Shopify naming", confidence: "high" },
  { name: "Ghost", category: "CMS", patterns: [/sitemap-(posts|pages|authors)\.xml/i], label: "sitemap index uses Ghost naming", confidence: "high" },
  { name: "Squarespace", category: "Site Builder", patterns: [/squarespace/i], label: "sitemap references Squarespace", confidence: "high" },
  { name: "Webflow", category: "Site Builder", patterns: [/website-files\.com/i], label: "sitemap references Webflow asset host", confidence: "medium" },
  { name: "Drupal", category: "CMS", patterns: [/sitemap\.xml\?page=\d/i], label: "paginated sitemap in Drupal style", confidence: "medium" },
];

/**
 * Markers of a bot-challenge or block interstitial. When a host serves one of
 * these, the response describes the edge, not the site, so nothing in it counts
 * as evidence about the platform.
 */
const INTERSTITIAL_MARKERS =
  /cf_chl_opt|__cf_chl|Just a moment\.\.\.|Attention Required!|Sorry, you have been blocked|Checking your browser before accessing|Enable JavaScript and cookies to continue/i;

/**
 * Cloudflare injects this script into ordinary successful responses as part of
 * bot scoring, so on its own it says nothing. It only indicates an interstitial
 * when it arrives with a status that means the request was refused.
 */
const CHALLENGE_SCRIPT = /cdn-cgi\/challenge-platform/i;
const REFUSAL_STATUSES = new Set([403, 429, 503]);

export function looksLikeInterstitial(body: string, status: number | null): boolean {
  if (INTERSTITIAL_MARKERS.test(body)) return true;
  return status !== null && REFUSAL_STATUSES.has(status) && CHALLENGE_SCRIPT.test(body);
}

const PATH_PROBES: PathProbe[] = [
  {
    path: "/wp-login.php",
    name: "WordPress",
    category: "CMS",
    accept: [200, 401, 403],
    // Deliberately excludes the bare string "wp-login": a 404 or block page that
    // echoes the requested path would otherwise confirm itself.
    confirm: /wp-submit|user_login|loginform/i,
  },
  {
    path: "/administrator/",
    name: "Joomla",
    category: "CMS",
    accept: [200, 401, 403],
    confirm: /joomla|com_login|mod-login|option=com_/i,
  },
  {
    path: "/user/login",
    name: "Drupal",
    category: "CMS",
    accept: [200, 401, 403],
    confirm: /drupal|user-login|edit-name|user-login-form/i,
  },
];

export interface FallbackOutcome {
  matches: TechMatch[];
  probes: ProbeResult[];
  probeWarning?: string;
}

function applyHints(
  text: string,
  rules: HintRule[],
  source: "robots" | "sitemap",
): TechMatch[] {
  const matches: TechMatch[] = [];
  for (const rule of rules) {
    if (rule.patterns.every((pattern) => pattern.test(text))) {
      matches.push({
        name: rule.name,
        category: rule.category,
        method: "fallback",
        source,
        confidence: rule.confidence,
        evidence: rule.label,
      });
    }
  }
  return matches;
}

/** Extracts the first Sitemap: directive so we check the sitemap the site actually declares. */
function sitemapFromRobots(robots: string, base: URL): URL | null {
  const match = robots.match(/^\s*sitemap:\s*(\S+)/im);
  if (!match) return null;
  try {
    const url = new URL(match[1], base);
    return url.hostname === base.hostname ? url : null;
  } catch {
    return null;
  }
}

/**
 * Mines the two things a site publishes about itself. The robots.txt body comes
 * from the gate, which already fetched it to decide what may be crawled -- so
 * reading it for platform hints costs no extra request.
 */
async function checkPublishedSignals(base: URL, gate: RobotsGate): Promise<TechMatch[]> {
  const matches: TechMatch[] = [];
  const policy = await gate.policyFor(base);

  if (policy.state === "rules" && policy.body) {
    matches.push(...applyHints(policy.body, ROBOTS_HINTS, "robots"));
  }

  const sitemapUrl = sitemapFromRobots(policy.body, base) ?? new URL("/sitemap.xml", base);
  const sitemap = await guardedFetch(sitemapUrl, {
    timeoutMs: 6000,
    maxBytes: 120_000,
    allowUrl: gate.allows,
  });

  if (sitemap.ok && sitemap.body && /<(urlset|sitemapindex|\?xml)/i.test(sitemap.body.slice(0, 500))) {
    matches.push(...applyHints(sitemap.body, SITEMAP_HINTS, "sitemap"));
  }

  return matches;
}

interface ControlStatuses {
  /** Response to a nonexistent `.php` file, mirroring /wp-login.php. */
  file: number | null;
  /** Response to a nonexistent directory, mirroring /administrator/. */
  directory: number | null;
  /** True when the host answers 2xx for URLs that cannot exist. */
  softNotFound: boolean;
  /** True when robots.txt put the control URLs themselves off-limits. */
  blockedByRobots: boolean;
}

/**
 * Establishes what "this path does not exist" looks like on this host, using
 * control URLs shaped like the real probes.
 *
 * Two failure modes make raw status codes worthless, and both are common:
 * hosts that answer 200 for everything, and WAFs that blanket-403 anything
 * resembling an admin path. A Ghost blog behind Cloudflare returns 403 for
 * /wp-login.php, which naively reads as WordPress. Comparing each probe
 * against a same-shaped control is what tells those apart.
 */
async function measureControls(base: URL, gate: RobotsGate): Promise<ControlStatuses> {
  const nonce = Math.random().toString(36).slice(2, 12);
  const [file, directory] = await Promise.all([
    guardedFetch(new URL(`/tde-probe-${nonce}.php`, base), {
      timeoutMs: 6000,
      maxBytes: 4000,
      allowUrl: gate.allows,
    }),
    guardedFetch(new URL(`/tde-probe-${nonce}/`, base), {
      timeoutMs: 6000,
      maxBytes: 4000,
      allowUrl: gate.allows,
    }),
  ]);

  const is2xx = (status: number | null) => status !== null && status >= 200 && status < 300;

  return {
    file: file.status,
    directory: directory.status,
    softNotFound: is2xx(file.status) || is2xx(directory.status),
    blockedByRobots: Boolean(file.blockedByRobots || directory.blockedByRobots),
  };
}

function skippedProbe(
  probe: PathProbe,
  skipped: NonNullable<ProbeResult["skipped"]>,
  note: string,
): ProbeResult {
  return { path: probe.path, status: null, meaningful: false, skipped, note };
}

async function runPathProbes(base: URL, gate: RobotsGate): Promise<FallbackOutcome> {
  const controls = await measureControls(base, gate);

  if (controls.softNotFound) {
    return {
      matches: [],
      probes: PATH_PROBES.map((probe) =>
        skippedProbe(probe, "soft-404", "not checked: this site answers 200 for any URL"),
      ),
      probeWarning:
        "Admin pages weren't checked. This site returns 200 even for pages that don't exist, so the status codes tell us nothing.",
    };
  }

  const settled = await Promise.all(
    PATH_PROBES.map(async (probe) => {
      const target = new URL(probe.path, base);

      // robots.txt is consulted before the request, not after. A disallowed path
      // is simply not fetched, and says so in the result.
      // `permits` rather than `allows`: this only checks, so it must not book a
      // Crawl-delay slot for a request that may never be made.
      if (!(await gate.permits(target))) {
        return {
          result: skippedProbe(probe, "robots", "not checked: robots.txt disallows this path"),
          match: null,
        };
      }

      /*
       * Without a control for this shape of URL there is no baseline, and every
       * status reads as informative. That is how a host whose control request
       * merely timed out turns an ordinary 403 into a confident "WordPress".
       * No baseline, no verdict.
       */
      const control = probe.path.endsWith("/") ? controls.directory : controls.file;
      if (control === null) {
        return {
          result: skippedProbe(
            probe,
            "no-baseline",
            controls.blockedByRobots
              ? "not checked: robots.txt disallows the control request we compare against"
              : "not checked: the control request failed, so there's nothing to compare against",
          ),
          match: null,
        };
      }

      const response = await guardedFetch(target, {
        timeoutMs: 6000,
        maxBytes: 40_000,
        allowUrl: gate.allows,
      });

      // A redirect can cross into an origin whose robots.txt forbids the target.
      if (response.blockedByRobots) {
        return {
          result: skippedProbe(probe, "robots", "not checked: robots.txt disallows this path"),
          match: null,
        };
      }

      const status = response.status;
      // A status the host also returns for a URL that cannot exist proves nothing.
      const informative = status !== null && status !== control;
      const challenged = looksLikeInterstitial(response.body, status);
      const confirmed = probe.confirm.test(response.body);

      /*
       * A bare 403 is ambiguous and the control cannot disambiguate it. WAFs
       * reject known attack paths -- /wp-login.php is the canonical one -- with
       * 403 while answering 404 for paths they have no rule for, and a control
       * URL is by construction not a known attack path. So a 403 only counts
       * when the page content backs it up.
       */
      const statusUsable =
        status !== null &&
        probe.accept.includes(status) &&
        (status !== 403 || confirmed);

      const hit = informative && statusUsable && !challenged;

      const result: ProbeResult = {
        path: probe.path,
        status,
        meaningful: hit,
        note: hit
          ? confirmed
            ? "confirmed by page content"
            : "path exists"
          : challenged
            ? "bot-challenge page, no signal"
            : status === 403
              ? "403 but unconfirmed, could be a firewall rule"
              : status !== null && status === control
                ? "same as control, no signal"
                : undefined,
      };

      const match: TechMatch | null = hit
        ? {
            name: probe.name,
            category: probe.category,
            method: "fallback",
            source: "path-probe",
            confidence: confirmed ? "high" : status === 200 ? "medium" : "low",
            evidence: confirmed
              ? `${probe.path} returned ${status} with matching page content`
              : `${probe.path} returned ${status}`,
          }
        : null;

      return { result, match };
    }),
  );

  const probes = settled.map((entry) => entry.result);
  const refusedByRobots = probes.filter((probe) => probe.skipped === "robots").length;

  return {
    matches: settled.map((entry) => entry.match).filter((m): m is TechMatch => m !== null),
    probes,
    probeWarning:
      refusedByRobots > 0
        ? `${refusedByRobots} of ${probes.length} admin pages weren't requested because robots.txt disallows them.`
        : undefined,
  };
}

/**
 * Second-pass detection for sites that expose no recognisable signature in
 * their HTML or headers. All secondary-signal checks run concurrently, and each
 * outbound request passes through the same robots.txt gate as the first pass.
 */
export async function runFallbackDetection(
  base: URL,
  gate: RobotsGate,
): Promise<FallbackOutcome> {
  const [hintMatches, probeOutcome] = await Promise.all([
    checkPublishedSignals(base, gate),
    runPathProbes(base, gate),
  ]);

  return {
    matches: [...hintMatches, ...probeOutcome.matches],
    probes: probeOutcome.probes,
    probeWarning: probeOutcome.probeWarning,
  };
}
